### ISSUE TITLE
[Bug]: Overzelous CSS

### ISSUE THREAD

**Issue by tonypartridger** [savannabits/filament-signature-pad#25]
### What happened?

Signaturepad 2.0.X is loading in it's own tailwindcss library! and as such classes are not scoped i.e.
```css
[type=button],
[type=reset],
[type=submit],
button {
  -webkit-appearance:button;
  background-color:initial;
  background-image:none;
}
:-moz-fo
```
should not exist.

### How to reproduce the bug

Install it

### Package Version

2.0.0-beta.1

### PHP Version

8.2

### Laravel Version

10.0

### Which operating systems does with happen with?

macOS
